# Generated by Django 5.2.16 on 2026-07-22 01:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='pagarme', max_length=30)),
                ('provider_event_id', models.CharField(blank=True, default='', max_length=120, null=True, unique=True)),
                ('event_type', models.CharField(max_length=120)),
                ('payload', models.JSONField()),
                ('payload_sha256', models.CharField(max_length=64)),
                ('headers_summary', models.JSONField(blank=True, default=dict)),
                ('authenticity_status', models.CharField(choices=[('VERIFIED', 'Verificado'), ('UNVERIFIED', 'Não verificado'), ('INVALID', 'Inválido')], default='UNVERIFIED', max_length=20)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Recebido'), ('PROCESSED', 'Processado'), ('IGNORED', 'Ignorado'), ('FAILED', 'Falhou')], default='RECEIVED', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento de Webhook',
                'verbose_name_plural': 'Eventos de Webhook',
                'ordering': ['-received_at'],
            },
        ),
    ]
