# Generated by Django 5.2.16 on 2026-07-22 01:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=80)),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('customer_phone', models.CharField(blank=True, default='', help_text='E.164 format', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount_cents', models.BigIntegerField()),
                ('installments', models.SmallIntegerField()),
                ('status', models.CharField(choices=[('CREATING', 'Criando'), ('CREATION_UNKNOWN', 'Resultado incerto'), ('CREATION_ERROR', 'Erro na criação'), ('ACTIVE', 'Ativo'), ('PAID', 'Pago'), ('CANCELED', 'Cancelado'), ('EXPIRED', 'Expirado'), ('REFUNDED', 'Reembolsado')], db_index=True, default='CREATING', max_length=20)),
                ('provider', models.CharField(default='pagarme', max_length=30)),
                ('provider_link_id', models.CharField(blank=True, default='', max_length=100, null=True, unique=True)),
                ('payment_url', models.TextField(blank=True, default='')),
                ('provider_status', models.CharField(blank=True, default='', max_length=80)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('creation_request', models.JSONField(blank=True, default=dict)),
                ('creation_response', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_links', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Link de Pagamento',
                'verbose_name_plural': 'Links de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_order_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_charge_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Aguardando'), ('PROCESSING', 'Processando'), ('PAID', 'Pago'), ('FAILED', 'Falhou'), ('REFUNDED', 'Reembolsado'), ('CHARGEDBACK', 'Chargeback')], default='PENDING', max_length=20)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('installments', models.SmallIntegerField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=100)),
                ('failure_message', models.CharField(blank=True, default='', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('raw_summary', models.JSONField(blank=True, default=dict)),
                ('payment_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='payment_links.paymentlink')),
            ],
            options={
                'verbose_name': 'Tentativa de Pagamento',
                'verbose_name_plural': 'Tentativas de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentlink',
            constraint=models.CheckConstraint(condition=models.Q(('installments__gte', 1), ('installments__lte', 3)), name='installments_range'),
        ),
        migrations.AddConstraint(
            model_name='paymentlink',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentlink',
            constraint=models.UniqueConstraint(fields=('seller', 'idempotency_key'), name='unique_seller_idempotency'),
        ),
    ]
