# Generated by Django 5.2.16 on 2026-07-23 16:21

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='O CNPJ deve conter exatamente 14 dígitos, sem máscara.', regex='^\\d{14}$')])),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(blank=True, default='', max_length=200)),
                ('registration_status', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('whatsapp_phone', models.CharField(blank=True, default='', max_length=20)),
                ('zip_code', models.CharField(max_length=8)),
                ('street', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('lookup_source', models.CharField(blank=True, default='', max_length=40)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.BigIntegerField()),
                ('due_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('internal_reference', models.CharField(blank=True, default='', max_length=80)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('CREATING', 'Processando'), ('CREATION_UNKNOWN', 'Confirmação pendente'), ('CREATION_ERROR', 'Erro na emissão'), ('PENDING', 'Aguardando pagamento'), ('PAID', 'Pago'), ('FAILED', 'Falhou'), ('EXPIRED', 'Vencido'), ('CANCELED', 'Cancelado'), ('PARTIALLY_CANCELED', 'Parcialmente cancelado'), ('REFUNDED', 'Estornado')], db_index=True, default='CREATING', max_length=24)),
                ('provider', models.CharField(default='pagarme', max_length=30)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('provider_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_charge_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('provider_status', models.CharField(blank=True, default='', max_length=80)),
                ('digitable_line', models.CharField(blank=True, default='', max_length=120)),
                ('barcode', models.CharField(blank=True, default='', max_length=120)),
                ('pdf_url', models.URLField(blank=True, default='', max_length=500)),
                ('company_snapshot', models.JSONField(default=dict)),
                ('creation_request', models.JSONField(blank=True, default=dict)),
                ('creation_response', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='self_created_boletos', to='sellers.seller')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boletos_created', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='sellers.seller')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletos', to='boletos.company')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'status'], name='boleto_seller_status_idx'), models.Index(fields=['due_date'], name='boleto_due_date_idx'), models.Index(fields=['company', 'created_at'], name='boleto_company_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='boleto_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('created_by_seller__isnull', True), ('created_by_user__isnull', False)), models.Q(('created_by_seller__isnull', False), ('created_by_user__isnull', True)), _connector='OR'), name='boleto_exactly_one_creator'), models.UniqueConstraint(fields=('seller', 'idempotency_key'), name='unique_boleto_seller_idempotency')],
            },
        ),
    ]
