# Generated by Django 5.2.16 on 2026-07-23 16:29

from django.db import migrations, models

import apps.boletos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('boletos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True, validators=[apps.boletos.validators.validate_cnpj]),
        ),
    ]
