# Generated by Django 5.2.16 on 2026-07-22 01:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('key_prefix', models.CharField(help_text='Prefixo visual para identificação', max_length=12)),
                ('key_hash', models.CharField(help_text='SHA-256 hash da chave', max_length=64)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente API',
                'verbose_name_plural': 'Clientes API',
            },
        ),
    ]
