# Generated by Django 5.2.16 on 2026-07-22 01:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_links', '__first__'),
        ('sellers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=80)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('deduplication_key', models.CharField(max_length=180, unique=True)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('DONE', 'Concluído'), ('DEAD', 'Permanente')], db_index=True, default='PENDING', max_length=20)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=100)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outbox de Notificação',
                'verbose_name_plural': 'Outbox de Notificações',
                'ordering': ['available_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_key', models.CharField(max_length=80)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('rendered_text', models.TextField()),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('QUEUED', 'Na fila'), ('SENDING', 'Enviando'), ('SENT', 'Enviado'), ('FAILED', 'Falhou'), ('DEAD', 'Permanente')], default='QUEUED', max_length=20)),
                ('provider_status', models.CharField(blank=True, default='', max_length=80)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages', to='payment_links.paymentlink')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
