# Generated by Django 5.2.16 on 2026-07-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='recipient_type',
            field=models.CharField(choices=[('seller', 'Vendedor'), ('customer', 'Cliente')], default='seller', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationoutbox',
            name='deduplication_key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
