# Generated by Django 5.2.16 on 2026-07-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationoutbox',
            options={'ordering': ['available_at'], 'verbose_name': 'Outbox de NotificaÃ§Ã£o', 'verbose_name_plural': 'Outbox de NotificaÃ§Ãµes'},
        ),
        migrations.AlterField(
            model_name='notificationoutbox',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Processando'), ('DONE', 'ConcluÃ\xaddo'), ('DEAD', 'Permanente')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
